apiVersion: batch/v1
kind: Job
metadata:
  name: slow-cooker1-deploy
spec:
  template:
    metadata:
      name: slow-cooker1-deploy
      labels:
        testrun: test1
    spec:
      containers:
      - name: slow-cooker
        image: buoyantio/slow_cooker:1.2.0
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: http_proxy
          value: http://l5d.linkerd.svc.cluster.local:4140
        command:
        - "/bin/sh"
        args:
        - "-c"
        - |
          slow_cooker \
            -qps 10 \
            -concurrency 1 \
            -interval 30s \
            http://hello.deploy
        ports:
        - name: slow-cooker
          containerPort: 9991
      restartPolicy: OnFailure
