apiVersion: batch/v1
kind: Job
metadata:
  name: slow-cooker1
spec:
  template:
    metadata:
      name: slow-cooker1
      labels:
        testrun: test1
    spec:
      restartPolicy: OnFailure
      containers:
      - name: slow-cooker
        image: buoyantio/slow_cooker:1.2.0
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: http_proxy
          value: $(NODE_NAME):4140
        command:
        - "/bin/sh"
        args:
        - "-c"
        - |
          slow_cooker \
            -qps 10000 \
            -concurrency 1 \
            -interval 90s \
            http://hello.$(POD_NAMESPACE)
