---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strest-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: strest-server
  template:
    metadata:
      labels:
        app: strest-server
    spec:
      containers:
      - name: strest-server
        image: buoyantio/strest-grpc:0.0.7
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: GRPC_GO_LOG_VERBOSITY_LEVEL
          value: "99"
        - name: GRPC_GO_LOG_SEVERITY_LEVEL
          value: "info"
        args:
        - "server"
        - "--address=:11111"
        ports:
        - name: grpc
          containerPort: 11111
---
apiVersion: v1
kind: Service
metadata:
  name: strest-server
spec:
  selector:
    app: strest-server
  clusterIP: None
  ports:
  - name: grpc
    port: 11111

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strest-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strest-client
  template:
    metadata:
      labels:
        app: strest-client
    spec:
      containers:
      - name: strest-client
        image: buoyantio/strest-grpc:0.0.7
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: GRPC_GO_LOG_VERBOSITY_LEVEL
          value: "99"
        - name: GRPC_GO_LOG_SEVERITY_LEVEL
          value: "info"
        args:
        - "client"
        - "--address=$(NODE_NAME):4340/strest-server.$(POD_NAMESPACE)"
        - "--connections=5"
        - "--totalTargetRps=100"
        - "--streams=5"
